### PR TITLE
allow passing args in envvars

### LINKED ISSUE #22: Request: Allow passing arguments via environment variables
Request: Allow passing arguments via environment variables. If I have time later this week I'll attempt it.

### PR DESCRIPTION
**Pull request by xdrie**
closes #22

### CODE REVIEW

**Comment by finefoot** [comment]
Why not user password, too?

**Comment by xdrie** [comment]
@finefoot Yours (#20) looks better. It's trivial to pass environment variables as arguments via the shell so I think that is the best solution.

**Comment by finefoot** [comment]
> It's trivial to pass environment variables as arguments via the shell so I think that is the best solution.

Yes, that's true. However, sometimes, it's not the safest way to pass arguments: https://unix.stackexchange.com/questions/85466/how-to-see-process-created-by-specific-user-in-unix-linux On the other hand, environment variables can be considered a lot more secret than arguments to a command line call: https://security.stackexchange.com/questions/14000/environment-variable-accessibility-in-linux/14009#14009 So your proposition to add support for environment variables makes sense in any case. :+1:

**Comment by russelldavies** [comment]
When I wrote this utility the use case in mind was that people would run this script once when they were switching or decommissioning a homeserver. It seems that quite a few people want to have this running continuously, I'm guessing as a backup strategy. So I'll be reorganizing how the archiver works. I'm thinking of making it run more like a daemon process with a config file.

So thanks for your pull request but I'm not going to merge it, rather take elements of it and use those.

**Pull request closed without merging**
